### ISSUE TITLE
The interval parameter is unused.

### ISSUE THREAD

**Issue by exceptDefeat** [wpp/simplestats#2]
The simpleStats function takes an interval parameter, perhaps with the intention of invoking the wrapper periodically.  This parameter appears not to be used.  

I'd suggest to use it with setInterval and to make the interval ID the return value of simpleStats so that the caller can cancel the callback, which also ensures that the object isn't held onto by the callback system.

I could also make the change if you agree and think it's necessary.

**Comment by wpp** [comment]
Hi @exceptDefeat,

Somehow didn't get an email from GitHub. Thanks for reporting that. I want to keep this simple so I removed the parameter.
